name: 'Install vyper'
description: 'Installs the vyper compiler.'
inputs:
  vyper-version:
    description: 'Version of vyper compiler to download.'
    required: false
    default: '0.4.0'
  vyper-commit:
    description: 'Commit of vyper compiler to download.'
    required: false
    default: 'e9db8d9f'
runs:
  using: "composite"
  steps:
    - name: Install vyper compiler
      shell: ${{ runner.os == 'Windows' && 'msys2 {0}' || 'bash' }}
      env:
        VYPER_DOWNLOAD_URL: "https://github.com/vyperlang/vyper/releases/download"
        VYPER_VERSION: ${{ inputs.vyper-version || '0.4.0' }}
        VYPER_COMMIT: ${{ inputs.vyper-commit || 'e9db8d9f' }}
      run: |
        VYPER_DOWNLOAD_FILENAME="vyper.${VYPER_VERSION}+commit.${VYPER_COMMIT}"
        case "$RUNNER_OS" in
          Linux*)
            OUTPUT=vyper
            VYPER_DOWNLOAD_EXTENSION=".linux"
            ;;
          macOS*)
            OUTPUT=vyper
            VYPER_DOWNLOAD_EXTENSION=".darwin"
            ;;
          Windows*)
            OUTPUT=vyper.exe
            VYPER_DOWNLOAD_EXTENSION=".windows.exe"
            ;;
        esac
        curl --location -o $OUTPUT \
          "${VYPER_DOWNLOAD_URL}/v${VYPER_VERSION}/${VYPER_DOWNLOAD_FILENAME}${VYPER_DOWNLOAD_EXTENSION}"
        chmod a+x ${OUTPUT}
        echo "${PWD}" >> "${GITHUB_PATH}"
