name: 'Install vyper'
description: 'Installs the vyper compiler.'
inputs:
  vyper-default-name:
    description: 'Default name of the vyper executable.'
    required: false
    default: 'vyper'
  vyper-versions:
    description: 'Version of vyper compiler to download.'
    required: false
    default: 'vyper.0.3.3+commit.48e326f0 vyper.0.3.9+commit.66b96705 vyper.0.3.10+commit.91361694 vyper.0.4.0+commit.e9db8d9f'
  vyper-version-latest:
    description: 'Latest version of vyper compiler to download.'
    required: false
    default: 'vyper.0.4.0+commit.e9db8d9f'
  output-dir:
    description: 'Output directory for the solc binaries.'
    required: false
    default: 'vyper-bins'
runs:
  using: "composite"
  steps:
    - name: Install vyper compiler
      shell: ${{ runner.os == 'Windows' && 'msys2 {0}' || 'bash' }}
      env:
        VYPER_DOWNLOAD_URL: "https://github.com/vyperlang/vyper/releases/download"
      run: |
        mkdir -p ${{ inputs.output-dir }}
        for VYPER_FULL_VERSION in ${{ inputs.vyper-versions }}; do
          case "$RUNNER_OS" in
            Linux*)
              VYPER_DOWNLOAD_EXTENSION=".linux"
              ;;
            macOS*)
              VYPER_DOWNLOAD_EXTENSION=".darwin"
              ;;
            Windows*)
              WIN_SUFFIX=.exe
              VYPER_DOWNLOAD_EXTENSION=".windows.exe"
              ;;
          esac
          VYPER_VERSION="$(echo "${VYPER_FULL_VERSION}" | sed -E 's/.*${{ inputs.vyper-default-name }}\.([0-9]+\.[0-9]+\.[0-9]+).*/\1/')"
          OUTPUT="${{ inputs.output-dir }}/${{ inputs.vyper-default-name }}-${VYPER_VERSION}${WIN_SUFFIX}"
          curl --location -o "${OUTPUT}" \
            "${VYPER_DOWNLOAD_URL}/v${VYPER_VERSION}/${VYPER_FULL_VERSION}${VYPER_DOWNLOAD_EXTENSION}"
          chmod a+x "${OUTPUT}"
          [ ${VYPER_FULL_VERSION} = ${{ inputs.vyper-version-latest }} ] && cp "${OUTPUT}" "${{ inputs.output-dir }}/${{ inputs.vyper-default-name }}${WIN_SUFFIX}"
        done
        echo "${PWD}/${{ inputs.output-dir }}" >> "${GITHUB_PATH}"
        ls -la ${PWD}/${{ inputs.output-dir }}
