//!
//! The `vyper` output selection flag.
//!

use std::str::FromStr;

///
/// The `vyper` output selection flag.
///
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, serde::Serialize, serde::Deserialize)]
pub enum Selection {
    /// The combined JSON.
    CombinedJson,
    /// The JSON LLL IR.
    IRJson,
    /// The metadata.
    Metadata,
    /// The AST.
    AST,
    /// The ABI data.
    ABI,
    /// The method identifiers.
    MethodIdentifiers,
    /// The storage layout.
    StorageLayout,
    /// The user documentation.
    UserDocumentation,
    /// The developer documentation.
    DeveloperDocumentation,

    /// The EraVM assembly.
    EraVMAssembly,
    /// The project metadata JSON.
    ProjectMetadata,
}

impl Selection {
    ///
    /// Whether the data can be retrieved from the `vyper` output.
    /// If it is not, it must be generated by `zkvyper`.
    ///
    pub fn is_requested_from_vyper(&self) -> bool {
        !matches!(
            self,
            Self::CombinedJson | Self::EraVMAssembly | Self::ProjectMetadata
        )
    }
}

impl FromStr for Selection {
    type Err = anyhow::Error;

    fn from_str(string: &str) -> anyhow::Result<Self> {
        Ok(match string {
            "combined_json" => Self::CombinedJson,
            "ir_json" => Self::IRJson,
            "metadata" => Self::Metadata,
            "ast" => Self::AST,
            "abi" => Self::ABI,
            "method_identifiers" => Self::MethodIdentifiers,
            "layout" => Self::StorageLayout,
            "userdoc" => Self::UserDocumentation,
            "devdoc" => Self::DeveloperDocumentation,
            "eravm_assembly" => Self::EraVMAssembly,
            "project_metadata" => Self::ProjectMetadata,
            string => anyhow::bail!("Unknown selection flag `{string}`"),
        })
    }
}

impl std::fmt::Display for Selection {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            Self::CombinedJson => write!(f, "combined_json"),
            Self::IRJson => write!(f, "ir_json"),
            Self::Metadata => write!(f, "metadata"),
            Self::AST => write!(f, "ast"),
            Self::ABI => write!(f, "abi"),
            Self::MethodIdentifiers => write!(f, "method_identifiers"),
            Self::StorageLayout => write!(f, "layout"),
            Self::UserDocumentation => write!(f, "userdoc"),
            Self::DeveloperDocumentation => write!(f, "devdoc"),
            Self::EraVMAssembly => write!(f, "eravm_assembly"),
            Self::ProjectMetadata => write!(f, "project_metadata"),
        }
    }
}
