name: 'Build LLVM'
description: 'Builds backend LLVM framework'
inputs:
  target:
    description: 'Specific build target triplet.'
    required: false
    default: ''
runs:
  using: "composite"
  steps:
    - name: Prepare environment
      if: runner.os == 'macOS'
      run: brew install cmake ninja
      shell: ${{ runner.os == 'Windows' && 'msys2 {0}' || 'bash' }}
    - name: Windows prepare msys2
      if: runner.os == 'Windows'
      uses: msys2/setup-msys2@v2
      with:
        path-type: inherit # Important to correctly update PATH
    - name: Prepare env
      if: runner.os == 'Windows'
      shell: ${{ runner.os == 'Windows' && 'msys2 {0}' || 'bash' }}
      env:
        MINGW64_DOWNLOAD_URL: "https://repo.msys2.org/mingw/mingw64"
        MINGW64_DOWNLOAD_FILENAME: "mingw-w64-x86_64-cmake-3.27.7-3-any.pkg.tar.zst"
      run: |
        pacman-key --refresh
        pacman -Sy
        curl -LO "$MINGW64_DOWNLOAD_URL/$MINGW64_DOWNLOAD_FILENAME"
        pacman --noconfirm -U "$MINGW64_DOWNLOAD_FILENAME"
        pacman --noconfirm -S --needed --overwrite \
          base-devel \
          git \
          ninja \
          mingw-w64-x86_64-clang \
          mingw-w64-x86_64-lld \
          mingw-w64-x86_64-rust \
          mingw-w64-x86_64-gcc-libs \
          mingw-w64-x86_64-gcc
        echo "/c/Users/runneradmin/.cargo/bin" >> $GITHUB_PATH
    - name: Define build target
      id: build-target
      if: inputs.target != ''
      shell: ${{ runner.os == 'Windows' && 'msys2 {0}' || 'bash' }}
      run: |
        rustup target add ${{ inputs.target }}
        echo "target=--target ${{ inputs.target }}" >> $GITHUB_OUTPUT
    - name: Clone LLVM framework
      shell: ${{ runner.os == 'Windows' && 'msys2 {0}' || 'bash' }}
      run: |
        cargo install compiler-llvm-builder ${{ steps.build-target.outputs.target }} \
          --git https://github.com/matter-labs/era-compiler-llvm-builder --branch aba-compiler-cache-support
        zkevm-llvm clone
    - name: Define ccache key
      shell: ${{ runner.os == 'Windows' && 'msys2 {0}' || 'bash' }}
      id: ccache-key
      run: |
        LLVM_BRANCH="$(git -C ./llvm rev-parse --abbrev-ref HEAD)"
        LLVM_SHORT_SHA="$(git -C ./llvm rev-parse --short HEAD)"
        echo "key=llvm-${LLVM_BRANCH}-${LLVM_SHORT_SHA}-${{ runner.os }}-${{ runner.arch }}" | tee -a "${GITHUB_OUTPUT}"
    - name: Set up compiler cache
      uses: hendrikmuhs/ccache-action@v1.2
      env:
        CCACHE_BASEDIR: ${{ github.workspace }}
        CCACHE_NOHASHDIR: "true"
        CCACHE_COMPILERCHECK: "content"
      with:
        key: ${{ steps.ccache-key.outputs.key }}
        restore-keys: ${{ steps.ccache-key.outputs.key }}
        append-timestamp: false
        max-size: "2G"
        verbose: 2
    - name: Build LLVM framework
      shell: ${{ runner.os == 'Windows' && 'msys2 {0}' || 'bash' }}
      env:
        CCACHE_BASEDIR: ${{ github.workspace }}
        CCACHE_NOHASHDIR: "true"
        CCACHE_COMPILERCHECK: "content"
        LIBSTDCPP_SOURCE_PATH: "C:/a/_temp/msys64/mingw64/lib/libstdc++.a"
      run: |
        zkevm-llvm build --use-ccache
