name: Build and release binaries

on:
  workflow_dispatch:
    inputs:
      ref:
        description: "Git REF to use for manual pre-release"
        required: true
        type: string
      prerelease_suffix:
        description: "Suffix which has been used for manual pre-release name"
        required: false
        type: string
        default: "notag"
      release_macos_amd64:
        description: "Release for MacOS amd64?"
        required: false
        type: boolean
        default: true
      release_macos_arm64:
        description: "Release for MacOS arm64?"
        required: false
        type: boolean
        default: true
      release_linux_amd64:
        description: "Release for Linux amd64?"
        required: false
        type: boolean
        default: true
      release_linux_arm64:
        description: "Release for Linux arm64?"
        required: false
        type: boolean
        default: true
      release_windows_amd64:
        description: "Release for Windows amd64?"
        required: false
        type: boolean
        default: true
  push:
    tags:
      - "v*.*.*"

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  build:
    strategy:
      matrix:
        include:
          - name: "MacOS x86"
            runner: macos-12-large
            release-suffix: macosx-amd64
            required: ${{ github.event.inputs.release_macos_amd64 || true }}
          - name: "MacOS arm64"
            runner: [self-hosted, macOS, ARM64]
            release-suffix: macosx-arm64
            required: ${{ github.event.inputs.release_macos_arm64 || true }}
          - name: "Linux x86"
            runner: matterlabs-ci-runner
            image: matterlabs/llvm_runner:ubuntu22-llvm15-latest
            target: "x86_64-unknown-linux-musl"
            release-suffix: linux-amd64
            required: ${{ github.event.inputs.release_linux_amd64 || true }}
          - name: "Linux ARM64"
            runner: matterlabs-ci-runner-arm
            image: matterlabs/llvm_runner:ubuntu22-llvm15-latest
            target: "aarch64-unknown-linux-musl"
            rustflags: "-C link-arg=-Wl,-Bstatic -C link-arg=-lc -C link-arg=-L/usr/lib/llvm-15/lib/clang/15.0.7/lib/linux/ -C link-arg=-lclang_rt.builtins-aarch64"
            release-suffix: linux-arm64
            required: ${{ github.event.inputs.release_linux_arm64 || true }}
          - name: "Windows"
            runner: windows-2022-github-hosted-16core
            release-suffix: windows-amd64-gnu
            required: ${{ github.event.inputs.release_windows_amd64 || true }}
    runs-on: ${{ matrix.runner }}
    container:
      image: ${{ matrix.image || '' }} # Special workaround to allow matrix builds with optional container
    name: ${{ matrix.name }}
    if: ${{ matrix.required }}
    steps:
      - name: Checkout source
        uses: actions/checkout@v4
      - name: Build LLVM
        uses: ./.github/actions/build-llvm
        with:
          target: ${{ matrix.target }}
      - name: Build zkvyper
        uses: ./.github/actions/build
        with:
          target: ${{ matrix.target }}
          rustflags: ${{ matrix.rustflags }}
      - name: Prepare binary
        shell: ${{ runner.os == 'Windows' && 'msys2 {0}' || 'bash' }}
        run: |
          mkdir -p ./releases/${RELEASE_SUFFIX}
          strip ./target/release/zkvyper
          [ ! -z "$GITHUB_REF_NAME" ] && TAG_SUFFIX="-${GITHUB_REF_NAME}"
          [ "$RUNNER_OS" = "Windows" ] && WIN_SUFFIX=".exe"
          mv ./target/${{ matrix.target }}/release/zkvyper${WIN_SUFFIX} \
            ./releases/${RELEASE_SUFFIX}/zkvyper-${RELEASE_SUFFIX}${TAG_SUFFIX}${WIN_SUFFIX}
      - name: Upload binary
        uses: actions/upload-artifact@v3
        with:
          name: release-${{ matrix.release-suffix }}
          path: releases
